// This is the content that appears on the Volunteer Benefits card
export const memberBenefits =
  "AWS Community Day is a dynamic event celebrating the AWS community, uniting cloud enthusiasts, developers, and professionals from diverse fields. This event highlights the expansive universe of AWS technologies, offering participants the chance to dive into educational sessions, engage in practical workshops, and expand their professional networks. Attendees will explore cutting-edge trends andpractical applications of AWS services, fostering a collaborative environment rich in knowledge exchange and innovation. The event is designed to provide a platform for learning and sharing, with opportunities to gain insights from AWS experts and industry leaders. Join us to connect with peers, enhance your AWS skills, and become part of a thriving community driven by shared learning and growth. As GenAI models grow more complex, successfully optimizing their accuracy, cost efficiency, and deployment velocity on AWS becomes both increasingly critical and challenging. This session will provide an end-to-end guide for GenAI teams to maximize their workload efficiency on AWS. We’ll provide an overview of the full GenAI development lifecycle then do a deep dive into progressive model optimization techniques—from prompt engineering to RAG and fine tuning—exploring how each incrementally improves accuracy while minimizing retraining compute requirements. Shifting gears, we’ll share AWS best practices for optimizing GenAI model packaging, deployment, and inference using containers and hardware acceleration. Monitoring and maintaining production GenAI workloads presents its own challenges, which we’ll address through observability, data drift detection, and model degradation monitoring techniques and tools on AWS. Attendees will walk away with a clear framework for incrementally optimizing their GenAI workloads throughout the machine learning lifecycle with an eye toward maximizing performance while keeping costs in check.";

// This is the content that appears on the Sponsor Benefits card
export const sponsorBenefits =
  "AWS Community Day is a dynamic event celebrating the AWS community, uniting cloud enthusiasts, developers, and professionals from diverse fields. This event highlights the expansive universe of AWS technologies, offering participants the chance to dive into educational sessions, engage in practical workshops, and expand their professional networks. Attendees will explore cutting-edge trends and practical applications of AWS services, fostering a collaborative environment rich in knowledge exchange and innovation. The event is designed to provide a platform for learning and sharing, with opportunities to gain insights from AWS experts and industry leaders. Join us to connect with peers, enhance your AWS skills, and become part of a thriving community driven by shared learning and growth.";

// This is the content that appears on the Volunteer Benefits card
export const volunteerBenefits =
  "AWS Community Day is a dynamic event celebrating the AWS community, uniting cloud enthusiasts, developers, and professionals from diverse fields. This event highlights the expansive universe of AWS technologies, offering participants the chance to dive into educational sessions, engage in practical workshops, and expand their professional networks. Attendees will explore cutting-edge trends and practical applications of AWS services, fostering a collaborative environment rich in knowledge exchange and innovation. The event is designed to provide a platform for learning and sharing, with opportunities to gain insights from AWS experts and industry leaders. Join us to connect with peers, enhance your AWS skills, and become part of a thriving community driven by shared learning and growth.";
